# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: androidcheck.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'androidcheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ndroidcheck.proto\"\x17\n\x06VmInfo\x12\r\n\x05vmUrl\x18\x01 \x01(\x0c\"z\n\x0bPayloadData\x12\x10\n\x08\x62ytecode\x18\x01 \x01(\x0c\x12\x1a\n\tVmUnknown\x18\x02 \x01(\x0b\x32\x07.VmInfo\x12\x12\n\nvmChecksum\x18\x03 \x01(\x0c\x12\x16\n\x0e\x65xpiryTimeSecs\x18\x04 \x01(\x05\x12\x11\n\tsignature\x18\t \x01(\x0c\"K\n\x14\x41ndroidCheckResponse\x12\x1d\n\x07payload\x18\x01 \x01(\x0b\x32\x0c.PayloadData\x12\x14\n\x0cunknownField\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'androidcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VMINFO']._serialized_start=22
  _globals['_VMINFO']._serialized_end=45
  _globals['_PAYLOADDATA']._serialized_start=47
  _globals['_PAYLOADDATA']._serialized_end=169
  _globals['_ANDROIDCHECKRESPONSE']._serialized_start=171
  _globals['_ANDROIDCHECKRESPONSE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
