# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: safetynet.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'safetynet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsafetynet.proto\"2\n\x0cSELinuxState\x12\x11\n\tsupported\x18\x01 \x01(\x08\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"-\n\tFileState\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\x0c\"\xe8\x01\n\rSafetyNetData\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x13\n\x0bpackageName\x18\x02 \x01(\t\x12\x17\n\x0fsignatureDigest\x18\x03 \x03(\x0c\x12\x12\n\nfileDigest\x18\x04 \x01(\x0c\x12\x16\n\x0egmsVersionCode\x18\x05 \x01(\x05\x12 \n\x0csuCandidates\x18\x06 \x03(\x0b\x32\n.FileState\x12#\n\x0cseLinuxState\x18\x07 \x01(\x0b\x32\r.SELinuxState\x12\x15\n\rcurrentTimeMs\x18\x08 \x01(\x03\x12\x10\n\x08googleCn\x18\t \x01(\x08\"@\n\rAttestRequest\x12\x15\n\rsafetyNetData\x18\x01 \x01(\x0c\x12\x18\n\x10\x64roidGuardResult\x18\x02 \x01(\t\" \n\x0e\x41ttestResponse\x12\x0e\n\x06result\x18\x02 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'safetynet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SELINUXSTATE']._serialized_start=19
  _globals['_SELINUXSTATE']._serialized_end=69
  _globals['_FILESTATE']._serialized_start=71
  _globals['_FILESTATE']._serialized_end=116
  _globals['_SAFETYNETDATA']._serialized_start=119
  _globals['_SAFETYNETDATA']._serialized_end=351
  _globals['_ATTESTREQUEST']._serialized_start=353
  _globals['_ATTESTREQUEST']._serialized_end=417
  _globals['_ATTESTRESPONSE']._serialized_start=419
  _globals['_ATTESTRESPONSE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
